### ISSUE TITLE
disable debug

### ISSUE THREAD

**Issue by Thorn-Inurcide** [Thorn-Inurcide/tde-slackbuilds#28]
The "core" Slackbuilds are already building release, so this doesn't apply to them, but do you think I should go through and disable debug on all the others? Mainly the Apps directory. I was just looking over the SlackBuilds for XFCE and KDE and they seem to have debug disabled throughout.

@ryanpcmcquen 
@Ray-V

**Comment by ryanpcmcquen** [comment]
Disable it.

**Comment by Ray-V** [comment]
Doesn't the
```
find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
```
section in the SB remove the debugging symbols? I'm guessing that this comes from the Alien's SlackBuild Toolkit scripts we're using, rather than Slackware scripts.

If it does, this is a good method of building without debugging symbols because it doesn't matter then whether or not the developer has set debugging on or off by default in the configuration - the end result will be binaries without debugging symbols.


The release option:
I've removed/not included that in the past where it has not been set up in the configuration [configure/CMakeLists.txt] files because it would have no affect on the build - it would be an unrecognized option.

**Comment by Thorn-Inurcide** [comment]
That's a good point, I didn't think of that. I'll just leave them as is then.
