### ISSUE TITLE
Uniformity in SlackBuilds

### ISSUE THREAD

**Issue by Thorn-Inurcide** [Thorn-Inurcide/tde-slackbuilds#30]
@Ray-V 
Does it matter to you if the slack-desc in the SB's are at the top or bottom of the SlackBuilds? Just wondering because to me it just seems like they should be at the end before the package is made(just a personal preference) and I wanted to start bringing the other slack-desc from the builds that have a separate file for it into the SlackBuilds as I like it there. I also wanted to put them all in the same place in all of the SlackBuilds. So if you have no objections or preferences on where it goes, I will begin doing that and place them all at the bottom.

**Comment by Ray-V** [comment]
@Thorn-Inurcide 
Just for the record because I see you've already done a lot of updates.

The reason they were at the top was that pre dialog script, a lot of variables and options had to be set up in the SlackBuild script and I felt that it would be best to have them all immediately obvious when the script file was opened up, and then as functions they could be called as required. As it's about the only remnant of those far off days, and the contents are available in the *.txt file, I think it doesn't matter now.

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Cool cool, I could have moved them back as needed, I know I had started including them in there too instead of a separate slack-desc..but I just felt like they were better at the bottom lol Anyways the point was to get all the SB's set up basically the same, so now when they get opened, I know whats going to be where no matter which one I opened, also removed comments I felt were really obvious like the #configure starts here ones.  Got them all nice and uniform. So that's done.
