### ISSUE TITLE
Koffice build failure

### ISSUE THREAD

**Issue by Thorn-Inurcide** [Thorn-Inurcide/tde-slackbuilds#40]
Koffice is failing to build Karbon for me. looks like an error related to libmagiccore 
Any ideas what would be causing this? In the meantime I'll try rebuilding it without graphicsmagic.

[koffice.gz](https://github.com/Thorn-Inurcide/tde-slackbuilds/files/1100709/koffice.gz)

**Comment by Thorn-Inurcide** [comment]
koffice just build after deselecting graphicsmagick

**Comment by Thorn-Inurcide** [comment]
everything else from koffice except chalk appears to be crashing now, built without graphicsmagick

**Comment by Thorn-Inurcide** [comment]
Launched from terminal:

kword

The Trinity ltdl loader was unable to dlopen() the shared library '/opt/trinity/                                                  lib64/trinity/libkwordpart.so' : 'libkotext.so.14: cannot open shared object fil                                                  e: No such file or directory'
The Trinity ltdl loader was unable to dlopen() the shared library '/opt/trinity/                                                  lib64/trinity/libkwordpart.so' : 'libkotext.so.14: cannot open shared object fil                                                  e: No such file or directory'
koffice (lib kofficecore): WARNING:

karbon

./karbon: error while loading shared libraries: libkarboncommon.so.14: cannot open shared object file: No such file or directory

kexi

./kexi: error while loading shared libraries: libkeximain.so.14: cannot open shared object file: No such file or directory

**kchart still launches**

kformula

The Trinity ltdl loader was unable to dlopen() the shared library '/opt/trinity/lib64/trinity/libkformulapart.so' : 'libkotext.so.14: cannot open shared object file: No such file or directory'
The Trinity ltdl loader was unable to dlopen() the shared library '/opt/trinity/lib64/trinity/libkformulapart.so' : 'libkotext.so.14: cannot open shared object file: No such file or directory'
koffice (lib kofficecore): WARNING:

I'm getting the idea that everything is looking for libpng14, any thoughts @Ray-V ?

**Comment by Thorn-Inurcide** [comment]
I don't know maybe I'll rebuild real quick without libpng14 just to see

**Comment by Thorn-Inurcide** [comment]
everything built and is launching without libpng14 and without graphicsmagick.

though the mentioned krita crashes exist that you found.

**Comment by Ray-V** [comment]
@Thorn-Inurcide
All the koffice apps build and run for me with krita/libpng14/GM selected.

Karbon will only build with ImageMagick, if it's installed, regardless of whether GraphicsMagick is installed, or selected in the build for krita.  
I forced a build with GM for Karbon, but it made no difference to what Karbon could save/load.

I don't know how these things work, but the 54 'undefined reference's:

> /usr/lib64/libMagickCore-6.Q16.so: undefined reference to \`DestroyPixelWand\'    
> /usr/lib64/libMagickCore-6.Q16.so: undefined reference to \`DrawPushPattern\'    
etc

in the build log are all references in libMagick**Wand**-6.Q16.so, not 'Core'

Maybe your Imagemagick/GraphicsMagick installations are screwed up?

I can only suggest you remove IM and GM from your system, re-install IM and set use krita[optional]/libpng14/GM in the koffice build and let it build and install a fresh GM.

**Comment by Thorn-Inurcide** [comment]
OK thanks ill do that tonight. Appreciate the help. 
Sent using Zoho Mail


---- On Tue, 27 Jun 2017 04:06:19 -0700 notifications@github.com wrote ----

@Thorn-Inurcide
All the koffice apps build and run for me with krita/libpng14/GM selected.

Karbon will only build with ImageMagick, if it's installed, regardless of whether GraphicsMagick is installed, or selected in the build for krita.
I forced a build with GM for Karbon, but it made no difference to what Karbon could save/load.

I don't know how these things work, but the 54 'undefined reference's:

/usr/lib64/libMagickCore-6.Q16.so: undefined reference to `DestroyPixelWand'
/usr/lib64/libMagickCore-6.Q16.so: undefined reference to `DrawPushPattern'
etc

in the build log are all references in libMagickWand-6.Q16.so, not 'Core'

Maybe your Imagemagick/GraphicsMagick installations are screwed up?

I can only suggest you remove IM and GM from your system, re-install IM and set use krita[optional]/libpng14/GM in the koffice build and let it build and install a fresh GM.

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
I was able to just try this. Still getting the same error after removing the deps.
I used slackpkg to install imagemagick and compiled GraphicsMagick again after removing it.
I'm on a clean install as well, only thing I've added is the Nvidia driver (my PC freezes without it) 
and ffmpeg and it's deps. Going to install a virtual machine and try in there and see what results I get

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
I removed imagemagicks entirely and trying the build again. If it works for me I'll just reinstall imagemagicks after it has built. And I'll still look at it in a VM as well. I'm also trying to see if I can get a friend to try it for me as well.

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
Alright it built for me and is working without imagemagicks installed. Don't know whats going on there but that's weird. I'll come back to this tonight and try it in a VM or 2. Should probably attempt a 32bit build anyways.

**Comment by Thorn-Inurcide** [comment]
If it builds without error I'll just close this. Somethings probably just corrupted on my machine

**Comment by Ray-V** [comment]
@Thorn-Inurcide 

It seems this is not an uncommon problem, this is just one page dealing with the issue:

http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=28634&p=127217

I think the instruction to use '--with-modules' could be the key because I'm using imagemagick-6.9.8_3-x86_64-1 from Slackware current which is configured with '--with-modules', but if you're using imagemagick from Slackware 14.2 that is configured with '--without-modules'.

**Comment by Thorn-Inurcide** [comment]
I am indeed on Slackware 14.2, I usually don't switch to current until the OS has set unmoving for a long time. There was a long wait between 14.1 and 14.2 which is why I was on it before. Software I was using demanded a lot of newer libraries and build tools than 14.1 had.

That's interesting to note though. I should just make note of this in the KNOWN-ISSUES file. So people can recompile imagemagick or just remove it before building koffice then reinstall it

**Comment by Thorn-Inurcide** [comment]
Hate to add an alternate slackbuild for it if it's already adjusted in -current and won't be an issue next Slackware release

**Comment by Thorn-Inurcide** [comment]
Thanks again @Ray-V

**Comment by Ray-V** [comment]
@Thorn-Inurcide

Looks like we've both forgotten that this problem came up with issue #23! The fix for karbon then was to introduce another set of LDFLAGS. That works, but because we've got one configuration for all of the koffice applications, it applies to all of them regardless of whether those extra ldflags are needed for each one.

So when I excluded those extra flags when useGM was selected in BUILD-TDE.sh, they were excluded for the karbon build as well. This didn't show for me because I'm using Slackware-current.

Configuration uses 'Magick-config' to identify the ldflags and libs needed where \*MAGICK\* variables are used in the Makefiles, but this only identifies libMagickCore, where for Sl 14.2 [IM version 6.9.4],  libMagickWand is also required.

So, let's put the hack where it's needed and use 'Wand-config' to identify the ldflags and libs needed - this will give libMagickWand and libMagickCore.

This will replace the issue 23 fix.
<pre>
--- Apps/koffice/koffice.SlackBuild
+++ Apps/koffice/koffice.SlackBuild
@@ -31,2 +30,0 @@
<span style="color:red">-## if GraphicsMagick not chosen in BUILD-TDE.sh, set up build to use ImageMagick</span>
<span style="color:red">-[[ ${USE_GM_LIBS:-} != yes ]] && IM_LDFLAGS=$($(which Magick++-config) --libs)</span>
@@ -57,0 +56,3 @@
<span style="color:blue">+## fix build problem for karbon - see issue 40 for details</span>
<span style="color:blue">+sed -i 's|(Magick-config|(Wand-config|' configure.in.in</span>
<span style="color:blue">+</span>
@@ -88 +89 @@
<span style="color:red">-LDFLAGS="${SLKLDFLAGS} ${IM_LDFLAGS:-}" \</span>
<span style="color:blue">+LDFLAGS="${SLKLDFLAGS}" \</span>
</pre>

I've tried builds with IM 6.9.8, and 6.9.4 [Sl64-14.2 .txz] on Sl64-current, and it works. Haven't tried it on Sl*-14.2.

--------------------

I haven't been able to build chalk/krita with Imagemagick - none of the builds I've tried use Imagemagick for the filters. In the build-koffice/filters/chalk/Makefile, the IM subdirectory entry [#IMAGEMAGICK_SUBDIR = magick] is always commented out even if IM is installed and GM isn't, which I haven't been able to figure out yet, but suspect it comes from one of the admin scripts.

But even if I try to force a build with IM by uncommenting IMAGEMAGICK_SUBDIR, there are too many errors which look like version mis-matches, so it's probably not worth the effort - let's just use GM.
<pre>
--- BUILD-TDE.sh
+++ BUILD-TDE.sh
@@ -401 +401 @@
<span style="color:red">-[3] The build will prefer ImageMagick to GraphicsMagick if both are installed but many image formats crash with IM, so GM is recommended.</span>
<span style="color:blue">+[3] GraphicsMagick will enable an extended range of image formats to be loaded and saved. ImageMagick should be an alternative, but building fails with that, so without GM, the range of supported image formats will be limited.</span>
@@ -403,2 +403,2 @@
<span style="color:red">-  If GM is chosen here, that preference will be overridden and GM will be added to the build list if not already selected or installed." \</span>
<span style="color:red">-28 75 3 \</span>
<span style="color:blue">+  If GM is chosen here, it will be added to the build list if not already selected or installed." \</span>
<span style="color:blue">+30 75 3 \</span>
@@ -469 +468,0 @@
<span style="color:red">-[[ $(cat $TMPVARS/Krita_OPTS 2>/dev/null) == *useGM* ]] && export USE_GM_LIBS=yes</span>
</pre>

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
I did indeed completely forget about issue 23 lol
I'll build koffice again tomorrow hopefully. Just wanted to comment on here real quick.

**Comment by Thorn-Inurcide** [comment]
@Ray-V 
this worked for me. Do you already have the changes made on your end, that you can just push this or issue a pull request? If not I will do it if you'd like. Thanks again for everything man.

Sorry I haven't been on top of this lately life has been kicking my ass lol
