### ISSUE TITLE
Luks volumes and Hal hardware abstraction layer and desktop

### ISSUE THREAD

**Issue by fastname3** [Thorn-Inurcide/tde-slackbuilds#48]
Hello
I want to comment about if you can add one working Hal in your tde-slackbuilts for mount luks volumes  on top, because now only can decrypted and mounted from shell,
Try to compile some hal sources successfully but does not mount from the desktop.
You can find  an old one for slackware 11.0 here, but dont work
http://slackbuilds.org/repository/11.0/system/hal/
here the oficcial web of hal
https://www.freedesktop.org/wiki/Software/hal/
I think this is a KNOWN-ISSUES
Sorry if I have a mistake I do not speak english
Thanks very much for your work regards.

**Comment by Thorn-Inurcide** [comment]
@fastname3 

Hi, by any chance did you try to add hal to the slackbuilds so it knows to build support for it? 
In tdelibs and tdebase needs this switch
-DWITH_HAL="ON"

by default it is off and needs manually turned on, I can add a check for hal but I just wanted to see if you turned that on or not. Thank you

**Comment by Thorn-Inurcide** [comment]
@fastname3 

Also what version of Slackware are you using???

**Comment by Thorn-Inurcide** [comment]
@Ray-V 

Am I reading this issue request right?

**Comment by fastname3** [comment]
Im using Slackware 14.2 for compile desktop, i believed tde-slackbuilds is for 14.2
I think i saw when you updated it from 14.1 to 14.2
one day I want to compile it in slack current  depends on what you tell me.

there are other slackbuilds for 14.1 but has the same error as mimetypes and hal
I think it has more dependencies like tde-ruby tde-perl or like that
If you do not know this one here:
http://www.inpito.org/trinity.php

what??
first you are going to put Hal and then not?
If you do not have it you must open luks from console not from the trinity desktop,
It's a bug by the way??
Hal problems currently??

I did not know the switch-DWITH_HAL="ON"
maybe is the problem hal compiles without errors, (from console ./configure not from scipts) but does not let the daemon rise

I think I understand that this has to be done
I need retouch tdebase.SlackBuild and tdelibs.SlackBuild adding:
-DWITH_HAL="ON"
because i want ON, if dont crash nothing
where and how should i put it in please??

I asked you because you know much more about the code of trinity,
about switch or like that i dont know and I'm already lost from the beginning trying to make it work

thanks very much for the answers I will try regards

**Comment by fastname3** [comment]
Hi again :)
I compiled tdebase.SlackBuild and tdelibs.SlackBuild adding:
-DWITH_HAL="ON"
at the end of switchs
Have hal installed  is required for tdebase after add the switch but not for tdelibs
unfortunately not work neither like this the hal daemon do not want to start and luks keep saying need hal.

the compilation change this libs:
 libtdecore.so.14.0.0 libtdeinit_ksmserver.so libtdeinit_kicker.so ksmserver.so kcm_keys.so kcm_media.so kded_mediamanager.so launcher_panelapplet.so

Keep trying regards

**Comment by Thorn-Inurcide** [comment]
@ I'm just confused here because I haven't even heard talk of Hal in so long that I don't know what you are asking. I don't know why you would need Hal for luks though. I will add those configure switches as a check for hal, please can you tell me the name of any hal .pc files for pkg-config? I thought you were asking me to actually add hal to the project which I won't do. as far as tde-ruby goes I believe that is the tdebindings package which I never compiled due to errors that I never resolved.

Also this does indeed compile on -current it does compile on -current, in fact the guy who made the dialog installer uses -current so the builds are run on both 14.2 and -current

**Comment by Thorn-Inurcide** [comment]
@fastname3  I honestly do not know anything about Hal to be able to help you with this. I don't run luks either. So I will have to install in a virtual machine and test in there for you.

**Comment by Ray-V** [comment]
Like @Thorn-Inurcide, I don't see why HAL is needed.

You say that a LUKS [partition?] will mount from the console, and it seems you want to mount it from the TDE GUI.

One way to achieve this is to set up a .desktop file in the Menu.

I haven't used LUKS, but assume that you'll have to enter a passphrase, so this should be 'Run in terminal'.

To add to TDE Menu:
Right-click start button | Menu editor | .. and create a 'New Item' [optionally in an existing [or new] folder].
Add the fields you want where Command is whatever you run in the console to mount the LUKS partition, and check 'Run in terminal' - the terminal will close once the Command has completed.

You'll need to create a separate .desktop file to unmount the LUKS partition.

Setting up a shortcut key is useful, especially in multi-key mode. You could have, for example, Ctrl-ml to mount LUKS and Ctrl-ul to unmount it.

The .desktop file should then be at ~/.local/share/applications/\<Name\>.desktop, and could be linked to the Desktop.

**Comment by fastname3** [comment]
Very thanks for the help Ray-V but that does not solve the problem only moves it

I think you have not understood me

a example:

when you put a external HD or pendrive on the fly in trinity desktop a windows dialog automatically pops up to ask if it opens or not,
when you say yes konqueror open a windows to show content of device and everyone happy

when you put a external HD or pendrive or whatever ENCRYPTED the same dialog ask you for a password to open,
When you put the pass tells you it does not open konqueror to show content because you need HAL installed and working

the only option is opens a konsole and writes:
"cryptsetup luksOpen /dev/sdc1 mounthere"
this order ask for the pass before mount,
you put the right pass and konqueror open a windows to show content.
and end of problem.

If you want I'll record a video or captures of the error.

The problem with Hal is not a fatal bug it's more like a comfort bug, does not prevent following but annoying,
It gives me much more anger than not all mimetypes are detected, is more stressful to work with textplain scripts etc.

fastname3 if you don't run luks either i teach you how very fast (No need install a virtual machine)

These are express instructions to encrypt a pendriver quickly less than a minute,
Just copy and paste phrase and enter, and follow the instructions.
punch a pendriver with little capacity so that it takes less,
the device example is sdh1 you should look where your external device is mounted

--Instructions:
umount /dev/sdh1
cryptsetup --verbose luksFormat /dev/sdh1
cryptsetup luksOpen /dev/sdh1 whatevername
ls -l /dev/mapper | grep whatevername
mkfs.ext4 /dev/mapper/whatevername
mkdir /mnt/ending
mount -t ext4 /dev/mapper/whatevername /mnt/ending
ls -la /mnt/ending
--End of instructions.

the last phrase is only to check if it is mounted
whatevername and ending are examples words can be changed for whatever word you want.


fastname3 sorry but i do not understand this
[[[please can you tell me the name of any hal .pc files for pkg-config?]]]
hal.pc and hal-storage.pc??
I copy you what goes inside hal.pc and hal-storage.pc files inside the folder pkgconfig/?
or just the files name??

I wanted to do more jump lines to distinguish but this github editor does not let me
regards

**Comment by Thorn-Inurcide** [comment]
@fastname3 I'm thinking this might be something you may want to report as a bug upstream to the trinity developers. I'm not sure if I can doing anything for you.

**Comment by Thorn-Inurcide** [comment]
@fastname3  although I now finally understand what you are trying to say. This seems like a core trinity code problem, and not something I can fix in a SlackBuild. On Linux there should be no need for us to call for HAL for any reason.

**Comment by Thorn-Inurcide** [comment]
@fastname3  just the names of that pkg-config files, i can run a pkg-config --exist command on it to turn a switch for HAL on if it's installed, But as I was saying, I shouldn't need to do this because Linux doesn't use HAL just FreeBSD does. I highly recommend talking to the trinity developers and their website and opening a bug for it

**Comment by Thorn-Inurcide** [comment]
@fastname3  Before you do that though, if you can do me a HUGE favor, maybe grab one of the TDE live ISO's from the website and run it, and see if the same problem exist in there? If it does report it as a bug?

**Comment by Thorn-Inurcide** [comment]
@fastname3 

It gives me much more anger than not all mimetypes are detected, is more stressful to work with textplain scripts etc.

this has been a problem since i ever first made slackbuilds for this. The only way around this so far is to manually add them. Like adding README and slack-desc to plain in the trinity settings i will take some screen shots real quick as an example.

1. go to file-associations 
2. go to text
3. select plain and add the README , *.md and slack-desc (and anything else: example ChangeLog)
4. go to x-shellscript and add *.SlackBuild

![snapshot2](https://user-images.githubusercontent.com/10385564/29304550-4295439e-8159-11e7-9bc8-13e3442aedb0.png)

![snapshot3](https://user-images.githubusercontent.com/10385564/29304591-760341b8-8159-11e7-9f68-133035ba5353.png)

![snapshot4](https://user-images.githubusercontent.com/10385564/29304603-88a86bb8-8159-11e7-8b04-43f96eb0752a.png)

![snapshot5](https://user-images.githubusercontent.com/10385564/29304616-9aaad594-8159-11e7-8342-813576c09914.png)

**Comment by Thorn-Inurcide** [comment]
@fastname3  just read this in the FAQ's 

15.16.	

How do the developers propose to transition away from HAL (hardware abstraction layer)?
	

The Trinity team developed a new native hardware support layer that is under testing. That new system will be enabled by default in a future release, but is available now in the development sources.


http://www.trinitydesktop.org/faq/misc.php

**Comment by Thorn-Inurcide** [comment]
@fastname3 

https://bugs.trinitydesktop.org/show_bug.cgi?id=2273

apparently it's already a bug report that has yet to be resolved
